### ISSUE TITLE
Can't copy album url on MAC using "copy" button

### ISSUE THREAD

**Issue by FUSAKLA** [Ruplahlava/Rupsha#9]
It just can't be done!!!

**Comment by Ruplahlava** [comment]
It uses flash app ZeroClipboard ( http://zeroclipboard.org/ ) can you check if it is working at all on their website?

I have to enable selecting on that field so it can be done manually.

**Comment by FUSAKLA** [comment]
error in my browser, flash is not allowed
but maybe would be good to have possibility to also without flash

**Comment by Ruplahlava** [comment]
Current state is, that you cant touch clipboard with javascript due to some restrictions.

**Comment by Ruplahlava** [comment]
https://github.com/Ruplahlava/Rupsha/commit/318a09025bd49f35dd6038a4a5b452a8de0e5207
Fixed
